packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.2.0
  '@radix-ui/react-accordion': ^1.2.4
  '@radix-ui/react-alert-dialog': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.4
  '@radix-ui/react-dialog': ^1.1.7
  '@radix-ui/react-dropdown-menu': ^2.1.7
  '@radix-ui/react-navigation-menu': ^1.2.6
  '@radix-ui/react-popover': ^1.1.7
  '@radix-ui/react-scroll-area': ^1.2.4
  '@radix-ui/react-select': ^2.1.7
  '@radix-ui/react-separator': ^1.1.3
  '@radix-ui/react-slot': ^1.2.0
  '@radix-ui/react-tabs': ^1.1.4
  '@tailwindcss/postcss': ^4
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-query': ^5.72.1
  '@tanstack/react-table': ^8.21.2
  '@types/lodash': ^4.17.16
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5.1.2
  axios: ^1.8.4
  cheerio: ^1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: ^1.1.1
  idb: ^8.0.2
  lefthook: ^2.0.8
  lodash: ^4.17.21
  lucide-react: 0.487.0
  next: 15.2.4
  next-themes: 0.4.6
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  turbo: ^2.6.3
  tw-animate-css: 1.4.0
  typescript: ^5
  vite: ^7.2.7

injectWorkspacePackages: true
