packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.10
  '@logtape/logtape': ^1.3.5
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-tabs': ^1.1.13
  '@supabase/supabase-js': 2.89.0
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-table': ^8.21.3
  '@types/cheerio': ^0.22.35
  '@types/lodash': ^4.17.21
  '@types/node': ^20.19.27
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@supabase/ssr': ^0.8.0
  'zod': ^4.2.1
  axios: ^1.13.2
  cheerio: ^1.1.2
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: ^1.1.1
  idb: ^8.0.3
  lefthook: ^2.0.8
  lodash: ^4.17.21
  lucide-react: 0.487.0
  next: 16.1.0
  next-themes: 0.4.6
  react: ^19.2.3
  react-dom: ^19.2.3
  supabase: ^2.67.3
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  ts-node: ^10.9.2
  tsx: ^4.21.0
  turbo: ^2.6.3
  tw-animate-css: 1.4.0
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-plugin-dts: 4.5.4

injectWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - supabase
  - lefthook
